config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  get '/cars', to: 'cars#index'
  get '/cars/:make', to: 'cars#show_make'



  resources :types do
    resources :foods
  end  

  # get "/types", to: "types#index" # get all food types
  # get "/types/:id", to: "types#show" # get one food type
  # get "/types/new", to: "types#new" # the page where you can add a new type
  # post "/types", to: "types#create" # create a new type
  # get "/types/:id/edit", to: "types#edit" # page where you can edit type
  # patch "types/:id", to: "types#update" # updates the type
  # delete "/types/:id", to: "types#destroy" # deletes the type

  


  # there are 7
  # get "/food_types", to: "food_types#index" # get all food types (index)
  # get "/food_types/:id", to: "food_types#show"
  # post "/food_types", to: "food_types#create"
  
  # "food_types#create"
  #, edit, destroy, update, new,
end

# Model == singular Car
# Controller == plural CarsController
# Methods are snake_case


# Steps:
# 0. Design database
# 1. routes.rb
# 2. models
# 3. controllers
# 4. views


# 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  def model_make
    "#{model} by #{make}"
  end


end


# model ==> speaking to the database

# controller ==> what you want it to do when you go to a route

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    cars = Car.all
    render_cars(cars)
  end

  def show_make
    make = params["make"] # jeep
    cars = Car.where(make: make)
    render_cars(cars)
  end

  private

  def render_cars(cars)
    render plain: cars.map {|car| car.model_make }.join(", ")
  end

end


# Add the ability to take in make as a param in the controller for displaying the cars

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    def create
        # render plain: params
        food_name = params[:food][:name]
        food_price = params[:food][:price]
        @type = Type.find(params[:type_id])
        @type.foods.create(name: food_name, price: food_price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  
  # def index
  #   friends = ["C", "Michaela", "Tara", "Ruta", "Julie"]
  #   render plain: friends.sample
  # end

  
  

end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  # before_action get_type

  def index
    @types = Type.all
  end

  def show
    # @type = Type.where(id: params[:id]).first
    # @type = Type.find_by(id: params[:id]) # can find by other variables
    @type = Type.find(params[:id]) # find by id
    @food = Food.new 

    # what's the difference find, find_by and where

    @foods = @type.foods

    render "show", layout: false
  end

  def new
    @type = Type.new
  end

  def create

    Type.create(name: params[:type][:name])
    redirect_to types_path

  end

  def edit
    # @type = Type.where(id: params[:id]).first
    # @type = Type.find_by(id: params[:id])
    @type = Type.find(params[:id])
  end

  def update
    new_type = params[:type][:name]
    @type = Type.find(params[:id])
    @type.update(name: new_type)

    redirect_to types_path
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end

  # private
  # def get_type
  #  @type = Type.find(params[:id])
  # end

end




# 1. list all the types
# 2. be able to click into each type and see all the foods of that type

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_for @type do |f| %>

  <%= f.text_field :name  %>
  <%= f.submit %>
  
<% end %>
  

app/views/types/edit.html.erb
<%= render "types/form" %>

app/views/types/index.html.erb
<h1>Types of Food</h1>

<div class="food-types">
<% @types.each do |type| %>

  <div>
    <div class="food-type" data-food-type-id="<%= type.id %>"><%= type.name %></div>
    <div class="items">When I click on a food type - food items will appear</div>
    <%= link_to 'Edit', edit_type_path(type) %>
    <%= link_to 'Delete', type, method: :delete %>
  </div>

<% end %>

</div>
<%= link_to 'new type of food', new_type_path %>

app/views/types/new.html.erb
<%= render "types/form" %>

app/views/types/show.html.erb
<%= form_for [@type, @food] do |f| %>

  <%= f.text_field :name  %>
  <%= f.text_field :price  %>
  <%= f.submit %>
  
<% end %>


<% @foods.each do |food| %>

  <div><%= food.name%> costs <%= food.price%></div>

<% end %>